[dev]
  publish = "_site"
  command = "npm run dev"
[build]
  command = "npm run build"
  functions = "src/functions/"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
[[plugins]]
package = "netlify-plugin-inline-functions-env"
   [plugins.inputs]
    include = ["GOOGLE_PRIVATE_KEY"]